project_id = "mdrxzwudhtmkyqcxwvcy"

[functions.process-document]
verify_jwt = false

[functions.workflow-start]
verify_jwt = false

[functions.workflow-worker]
verify_jwt = false

[functions.workflow-maintenance]
verify_jwt = false
