project_id = "mdrxzwudhtmkyqcxwvcy"

[functions.workflow-start]
verify_jwt = false

[functions.workflow-worker]
verify_jwt = false

[functions.workflow-maintenance]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
