// Save a chat export (Markdown or PDF) to the connected Google Drive account.
// Read-only on local data: never re-indexes the exported file.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers':
    'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const GATEWAY_UPLOAD =
  'https://connector-gateway.lovable.dev/google_drive/upload/drive/v3/files';

const MAX_MD = 10 * 1024 * 1024;
const MAX_PDF = 25 * 1024 * 1024;

const ALLOWED_MIME = new Set(['text/markdown', 'application/pdf']);

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

function sanitizeFilename(s: string): string {
  return (s || 'export')
    .replace(/[\\/\r\n\t]+/g, '_')
    .replace(/[^\w.\- ()]+/g, '_')
    .slice(0, 200) || 'export';
}

function base64ToBytes(b64: string): Uint8Array {
  const clean = b64.replace(/\s+/g, '');
  const bin = atob(clean);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const lovableKey = Deno.env.get('LOVABLE_API_KEY');
    const driveKey = Deno.env.get('GOOGLE_DRIVE_API_KEY');
    if (!lovableKey || !driveKey) {
      return json(
        {
          error: 'google_drive_not_connected',
          message: 'Google Drive is not connected for this project.',
        },
        400,
      );
    }

    const supaUrl = Deno.env.get('SUPABASE_URL')!;
    const supaAnon = Deno.env.get('SUPABASE_ANON_KEY')!;
    const authHeader = req.headers.get('Authorization') || '';

    const userClient = createClient(supaUrl, supaAnon, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: userData, error: userErr } = await userClient.auth.getUser();
    if (userErr || !userData?.user) return json({ error: 'unauthorized' }, 401);
    const userId = userData.user.id;

    const body = await req.json().catch(() => ({}));
    const format = body?.format as 'markdown' | 'pdf';
    const mimeType = String(body?.mimeType || '');
    const filename = sanitizeFilename(String(body?.filename || ''));
    const contentBase64 = String(body?.contentBase64 || '');
    const contextType = body?.contextType as 'project' | 'notebook';
    const contextId = body?.contextId ? String(body.contextId) : null;
    const chatId = body?.chatId ? String(body.chatId) : null;
    const metadata =
      body?.metadata && typeof body.metadata === 'object'
        ? (body.metadata as Record<string, unknown>)
        : {};

    if (
      (format !== 'markdown' && format !== 'pdf') ||
      !ALLOWED_MIME.has(mimeType) ||
      !filename ||
      !contentBase64 ||
      !contextId ||
      (contextType !== 'project' && contextType !== 'notebook')
    ) {
      return json(
        { error: 'invalid_input', message: 'Missing or invalid export parameters.' },
        400,
      );
    }

    // Validate MIME matches format.
    if (
      (format === 'markdown' && mimeType !== 'text/markdown') ||
      (format === 'pdf' && mimeType !== 'application/pdf')
    ) {
      return json({ error: 'invalid_input', message: 'Format and MIME type mismatch.' }, 400);
    }

    // Decode bytes & size-check.
    let bytes: Uint8Array;
    try {
      bytes = base64ToBytes(contentBase64);
    } catch {
      return json({ error: 'invalid_input', message: 'Invalid base64 content.' }, 400);
    }
    const cap = format === 'markdown' ? MAX_MD : MAX_PDF;
    if (bytes.byteLength > cap) {
      return json(
        {
          error: 'file_too_large',
          message:
            'This export is too large to save to Drive. Try Markdown or reduce included source snippets.',
        },
        413,
      );
    }

    // RBAC: viewer is enough to export a chat the user can already see.
    const { data: hasPerm, error: permErr } = await userClient.rpc('check_item_permission', {
      p_user_id: userId,
      p_item_id: contextId,
      p_item_type: contextType,
      p_min_role: 'viewer',
    });
    if (permErr || !hasPerm) {
      return json(
        { error: 'forbidden', message: 'You do not have access to this chat.' },
        403,
      );
    }

    // Build multipart/related upload payload.
    const driveMetadata: Record<string, unknown> = {
      name: filename,
      mimeType,
      description: 'Generated by Researcher',
      appProperties: {
        source: 'researcher',
        contextType,
        contextId,
        ...(chatId ? { chatId } : {}),
        exportedAt:
          typeof metadata.exportedAt === 'string'
            ? metadata.exportedAt
            : new Date().toISOString(),
      },
    };

    const boundary =
      '----researcher-' + crypto.randomUUID().replace(/-/g, '');
    const enc = new TextEncoder();
    const head = enc.encode(
      `--${boundary}\r\n` +
        'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
        JSON.stringify(driveMetadata) +
        `\r\n--${boundary}\r\n` +
        `Content-Type: ${mimeType}\r\n` +
        'Content-Transfer-Encoding: binary\r\n\r\n',
    );
    const tail = enc.encode(`\r\n--${boundary}--\r\n`);
    const multipartBody = new Uint8Array(head.byteLength + bytes.byteLength + tail.byteLength);
    multipartBody.set(head, 0);
    multipartBody.set(bytes, head.byteLength);
    multipartBody.set(tail, head.byteLength + bytes.byteLength);

    const uploadUrl = new URL(GATEWAY_UPLOAD);
    uploadUrl.searchParams.set('uploadType', 'multipart');
    uploadUrl.searchParams.set('fields', 'id,name,mimeType,webViewLink,webContentLink');

    const uploadResp = await fetch(uploadUrl.toString(), {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${lovableKey}`,
        'X-Connection-Api-Key': driveKey,
        'Content-Type': `multipart/related; boundary=${boundary}`,
      },
      body: multipartBody,
    });

    if (!uploadResp.ok) {
      const text = await uploadResp.text().catch(() => '');
      console.error('[gdrive-export-chat] upload fail', uploadResp.status, text);
      if (uploadResp.status === 401) {
        return json(
          {
            error: 'google_drive_not_connected',
            message: 'Google Drive is not connected for this project.',
          },
          400,
        );
      }
      if (uploadResp.status === 403) {
        return json(
          {
            error: 'google_drive_write_scope_missing',
            message:
              'Google Drive write access is not connected. Reconnect Google Drive with file create/upload scope.',
          },
          403,
        );
      }
      if (uploadResp.status === 413) {
        return json(
          { error: 'file_too_large', message: 'Export is too large to save to Drive.' },
          413,
        );
      }
      return json(
        { error: 'upload_failed', message: `Drive upload failed (${uploadResp.status}).` },
        502,
      );
    }

    const file = await uploadResp.json();
    return json({
      fileId: file.id,
      name: file.name,
      mimeType: file.mimeType,
      webViewLink: file.webViewLink ?? null,
      webContentLink: file.webContentLink ?? null,
    });
  } catch (err: any) {
    console.error('[gdrive-export-chat] unexpected', err);
    return json(
      { error: 'internal_error', message: err?.message || 'Unknown error' },
      500,
    );
  }
});
