// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id, email, display name, and plan for the connected Researcher account.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("profiles").select("id, display_name, username, plan").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const profile = {
      userId: ctx.getUserId(),
      email: ctx.getUserEmail() ?? null,
      displayName: data?.display_name ?? data?.username ?? null,
      plan: data?.plan ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-plant-cases.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { z } from "npm:zod@^3.25.76";
var list_plant_cases_default = defineTool2({
  name: "list_plant_cases",
  title: "List plant cases",
  description: "List the signed-in user's Plant Advisor cases with title, status, goal, and confirmed identification if any. Ordered by most recently updated.",
  inputSchema: {
    limit: z.number().int().positive().max(50).optional().describe("Maximum number of cases to return (default 20, max 50)."),
    status: z.enum([
      "draft",
      "ready_for_identification",
      "identified",
      "diagnosed",
      "treated",
      "archived"
    ]).optional().describe("Filter by plant case status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let q = supabase.from("plant_cases").select(
      "id, title, status, user_goal, location_text, crop_context, confirmed_scientific_name, confirmed_common_name, identified_scientific_name, identified_common_name, created_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const cases = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(cases) }],
      structuredContent: { cases, count: cases.length }
    };
  }
});

// src/lib/mcp/tools/get-plant-case.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_plant_case_default = defineTool3({
  name: "get_plant_case",
  title: "Get plant case",
  description: "Return a single Plant Advisor case for the signed-in user, including its confirmed identification and confirmed disease diagnosis if present.",
  inputSchema: {
    caseId: z2.string().uuid().describe("Plant case id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ caseId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: pc, error } = await supabase.from("plant_cases").select("*").eq("id", caseId).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!pc) {
      return { content: [{ type: "text", text: "Plant case not found" }], isError: true };
    }
    const { data: diag } = await supabase.from("plant_diagnoses").select("id, rank, score, problem_type, name, description, affected_organs, is_confirmed, confirmed_at, language").eq("case_id", caseId).eq("is_confirmed", true).maybeSingle();
    const payload = { case: pc, confirmedDiagnosis: diag ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-notebooks.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_notebooks_default = defineTool4({
  name: "list_notebooks",
  title: "List notebooks",
  description: "List notebooks the signed-in user owns or has been shared with, ordered by most recently updated.",
  inputSchema: {
    limit: z3.number().int().positive().max(50).optional().describe("Maximum number of notebooks to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("notebooks").select("id, title, description, language, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const notebooks = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(notebooks) }],
      structuredContent: { notebooks, count: notebooks.length }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool5({
  name: "list_projects",
  title: "List projects",
  description: "List projects the signed-in user owns or has been shared with, ordered by most recently updated.",
  inputSchema: {
    limit: z4.number().int().positive().max(50).optional().describe("Maximum number of projects to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("projects").select("id, name, description, language, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const projects = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(projects) }],
      structuredContent: { projects, count: projects.length }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mdrxzwudhtmkyqcxwvcy";
var mcp_default = defineMcp({
  name: "researcher-mcp",
  title: "Researcher",
  version: "0.1.0",
  instructions: "Read-only tools for the signed-in Researcher user. Use `whoami` to verify the connected account, `list_projects` and `list_notebooks` to browse the user's workspace, and `list_plant_cases`/`get_plant_case` to inspect Plant Advisor cases including confirmed identifications and disease diagnoses. All tools scope to the authenticated user; do not fabricate ids.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_projects_default,
    list_notebooks_default,
    list_plant_cases_default,
    get_plant_case_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
