// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  SUPABASE_PUBLISHABLE_KEY,
  SUPABASE_URL,
  SUPABASE_ENV_SOURCE,
} from '@/config/env';

if (SUPABASE_ENV_SOURCE.url === 'fallback' || SUPABASE_ENV_SOURCE.key === 'fallback') {
  console.warn(
    '[supabase] Missing VITE_* and runtime env values. Using hardcoded fallback Supabase config.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});