// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const FALLBACK_SUPABASE_URL = 'https://mdrxzwudhtmkyqcxwvcy.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kcnh6d3VkaHRta3lxY3h3dmN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5OTQ2NjAsImV4cCI6MjA4OTU3MDY2MH0.2EZVGthInapEDDEpTD3DSTHde92lMmCNd_H9V97gyC8';

type RuntimeEnv = {
  VITE_SUPABASE_URL?: string;
  VITE_SUPABASE_PUBLISHABLE_KEY?: string;
};

function resolveRuntimeEnv(): RuntimeEnv {
  if (typeof window === 'undefined') return {};
  const win = window as unknown as {
    __ENV__?: RuntimeEnv;
    LOVABLE_ENV?: RuntimeEnv;
  };
  return {
    ...(win.__ENV__ ?? {}),
    ...(win.LOVABLE_ENV ?? {}),
  };
}

const runtimeEnv = resolveRuntimeEnv();
export const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  runtimeEnv.VITE_SUPABASE_URL ||
  FALLBACK_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  runtimeEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
  FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    '[supabase] Missing VITE_* env vars at build runtime. Using runtime/fallback values instead.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});